=== 02manoj92/ocsf-schema/test/object.schema.json
{
    "$id": "https://schema.ocsf.io/object.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Object",
    "type": "object",
    "required": [
        "description",
        "caption",
        "name",
        "attributes"
    ],
    "properties": {
        "description": {
          "type": "string",
          "description": "A concise description of the object."
        },
        "caption": {
          "type": "string",
          "description": "A short, human friendly name for the object."
        },
        "name": {
          "type": "string",
          "description": "A name of the object. It must be a unique name. The name is all lower case letters, combine words using underscore.",
          "pattern": "^[a-z_]*$"
        },
        "attributes": {
            "type": "object",
            "description": "A dictionary of attributes for the object.",
            "properties": {
                "$include": {
                    "description": "A reference to another schema for attributes to include.",
                    "oneOf": [
                        {
                            "type": "string",
                            "format": "uri-reference"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string",
                                "format": "uri-reference"
                            }
                        }
                    ]
                }
            },
            "additionalProperties": {
                "type": "object",
                "properties": {
                    "description": {
                        "type": "string",
                        "description": "The description of the attribute."
                    },
                    "group": {
                        "type": "string",
                        "description": "The group that the attribute is a part of.",
                        "enum": ["context", "classification", "occurrence", "primary"]
                    },
                    "requirement": {
                        "type": "string",
                        "description": "The requirement placed on the attribute for inclusion in the schema.",
                        "enum": ["optional", "recommended", "required"]
                    }
                }
            }
        }
    }
}

=== 02manoj92/ocsf-schema/objects/server.json
{
  "caption": "Server",
  "name": "server",
  "description": "The Server object describes the server responding to a client request.",
  "attributes": {
    "name": {
      "description": "The name of the server.",
      "requirement": "optional"
    },
    "os": {
      "requirement": "optional"
    },
    "product": {
      "requirement": "optional"
    },
    "version": {
      "description": "The server protocol version.",
      "requirement": "recommended"
    },
    "uid": {
      "description": "The unique server identifier.",
      "requirement": "required"
    }
  }
}

=== 02manoj92/ocsf-schema/objects/dce_rpc.json
{
  "caption": "Distributed Computing Environment/Remote Procedure Calls (DCE/RPC)",
  "name": "dce_rpc",
  "description": "The DCE/RPC object describes the remote procedure call system for distributed computing environments.",
  "attributes": {
    "flags": {
      "description": "The list of interfaces",
      "requirement": "required"
    },
    "network_interfaces": {
      "description": "The list of DCE/RPC interfaces",
      "requirement": "optional"
    }
  }
}
