=== 02manoj92/ocsf-schema/metaschema/profile.schema.json
{
    "$id": "https://schema.ocsf.io/profile.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Profile",
    "type": "object",
    "required": [
        "caption",
        "description",
        "meta",
        "name",
        "attributes"
    ],
    "properties": {
        "annotations": {
            "type": "object",
            "description": "Annotations for this profile describing categories it belongs in."
        },
        "caption": {
            "type": "string",
            "description": "A short, human friendly name for the profile."
        },
        "description": {
          "type": "string",
          "description": "A concise description of the profile."
        },
        "meta": {
            "type": "string",
            "description": "A value indicating the type of this profile.",
            "enum": ["profile"]
        },
        "name": {
            "type": "string",
            "description": "A name of the profile. It must be a unique name. The name is all lower case letters, combine words using underscore.",
            "pattern": "^[a-z0-9_]*$"
        },
        "attributes": {
            "type": "object",
            "description": "A dictionary of attributes for the profile.",
            "additionalProperties": {
                "$ref": "attribute.schema.json"
            }
        }
    },
    "additionalProperties": false
}

=== 02manoj92/ocsf-schema/profiles/network_proxy.json
{
  "description": "The attributes that identify network proxy attributes.",
  "meta": "profile",
  "caption": "Network Proxy",
  "name": "network_proxy",
  "annotations": {
    "group": "primary"
  },
  "attributes": {
    "proxy_connection_info": {
      "description": "The connection information from the network proxy to the remote server.",
      "requirement": "recommended"
    },
    "proxy_http_request": {
      "description": "The HTTP Request Object documents attributes of a request made from the network proxy to the remote server.",
      "requirement": "optional"
    },
    "proxy_http_response": {
      "description": "The HTTP Response from the remote server to the network proxy.",
      "requirement": "optional"
    },
    "proxy_traffic": {
      "description": "The network traffic refers to the amount of data moving across a network, from proxy to remote server at a given point of time. Intended to be used alongside Network Connection.",
      "requirement": "recommended"
    },
    "proxy_tls": {
      "description": "The Transport Layer Security (TLS) attributes from the network proxy to the remote server.",
      "requirement": "recommended"
    }
  }
}

=== 02manoj92/ocsf-schema/profiles/securitycontrol.json
{
  "description": "The attributes that identify security controls such as malware or policy violations.",
  "meta": "profile",
  "caption": "Security Controls",
  "name": "securitycontrol",
  "annotations": {
    "group": "primary"
  },
  "attributes": {
    "attacks": {
      "requirement": "recommended"
    },
    "disposition": {
      "requirement": "optional"
    },
    "disposition_id": {
      "requirement": "required"
    },
    "malware": {
      "requirement": "optional"
    }
  }
}

=== 02manoj92/ocsf-schema/profiles/reputation.json
{
  "description": "The domain reputation information.",
  "meta": "profile",
  "caption": "Domain Reputation",
  "name": "reputation",
  "attributes": {
    "categories": {
      "description": "A list of URL categories as defined by the event source.",
      "requirement": "recommended"
    },
    "category_ids": {
      "requirement": "recommended"
    },
    "domain_info": {
      "requirement": "recommended"
    },
    "parent_categories": {
      "requirement": "recommended"
    },
    "provider": {
      "description": "The provider of the reputation and category information.",
      "requirement": "recommended"
    }
  }
}

=== 02manoj92/ocsf-schema/profiles/domain_reputation.json
{
  "description": "The domain reputation information.",
  "meta": "profile",
  "caption": "Domain Reputation",
  "name": "domain_reputation",
  "attributes": {
    "domain_info": {
      "requirement": "recommended"
    },
    "provider": {
      "description": "The domain reputation provider information.",
      "requirement": "recommended"
    },
    "reputation": {
      "description": "The domain reputation.",
      "requirement": "optional"
    }
  }
}

=== 02manoj92/ocsf-schema/profiles/security_control.json
{
  "description": "The attributes including disposition that represent the outcome of a security control including but not limited to access control, malware or policy violation, network proxy, firewall, or data control.  The profile is intended to augment activities or findings with an outcome where a security control has intervened.",
  "meta": "profile",
  "caption": "Security Control",
  "name": "security_control",
  "annotations": {
    "group": "primary"
  },
  "attributes": {
    "action": {
      "caption": "Action",
      "description": "The normalized caption of 'action_id' or the source specific action.",
      "requirement": "optional"
    },
    "action_id": {
      "caption": "Action ID",
      "description": "The normalized action taken by a control or other policy-based system leading to an outcome or disposition. Note that <code>Other</code> is not an option. No action would equate to <code>Allowed</code>. Refer to <code>disposition_id</code> for the outcome of the action.",
      "enum": {
        "0": {
          "caption": "Unknown",
          "description": "The action was unknown. The <code>disposition_id</code> attribute may still be set to a non-unknown value."
        },
        "1": {
          "caption": "Allowed",
          "description": "The activity was allowed. The <code>disposition_id</code> attribute must be set to a value that conforms to this action, for example 'Allowed', 'Approved', 'No Action', 'Count' etc."
        },
        "2": {
          "caption": "Denied",
          "description": "The attempted activity was denied. The <code>disposition_id</code> attribute must be set to a value that conforms to this action, for example 'Blocked', 'Quarantined', 'Isolated', 'Dropped', 'Access Revoked, 'Rejected',  etc."
        }
      },
      "requirement": "required"
    },
    "attacks": {
      "requirement": "optional"
    },
    "authorizations": {
      "requirement": "optional"
    },
    "disposition": {
      "requirement": "optional"
    },
    "disposition_id": {
      "requirement": "required",
      "enum": {
        "99": {
          "caption": "Other",
          "description": "The disposition is not listed.  The disposition field should be populated with a label."
        },
        "0": {
          "caption": "Unknown",
          "description": "The disposition was not known."
        },
        "1": {
          "caption": "Allowed",
          "description": "Granted access or allowed the action to the protected resource. For firewalls or proxies, the request is forwarded and is a network terminating action."
        },
        "2": {
          "caption": "Blocked",
          "description": "Denied access or blocked the action to the protected resource. For firewalls or proxies, this is a network terminating action."
        },
        "3": {
          "caption": "Quarantined",
          "description": "A suspicious file or other content was moved to a benign location."
        },
        "4": {
          "caption": "Isolated",
          "description": "A session was isolated on the network or within a browser."
        },
        "5": {
          "caption": "Deleted",
          "description": "A file or other content was deleted."
        },
        "6": {
          "caption": "Dropped",
          "description": "For firewalls, a threat was detected and the associated session was dropped."
        },
        "7": {
          "caption": "Custom Action",
          "description": "A custom action was executed such as running of a command script.  Use the <code>message</code> attribute of the base class for details."
        },
        "8": {
          "caption": "Approved",
          "description": "A request or submission was approved.  For example, when a form was properly filled out and submitted.  This is distinct from '<code>Allowed</code>'."
        },
        "9": {
          "caption": "Restored",
          "description": "A quarantined file or other content was restoerd to its original location."
        },
        "10": {
          "caption": "Exonerated",
          "description": "A suspicious or risky entity was deemed to no longer be suspicious (re-scored)."
        },
        "11": {
          "caption": "Corrected",
          "description": "A corrupt file or configuration was corrected."
        },
        "12": {
          "caption": "Partially Corrected",
          "description": "A corrupt file or configuration was partially corrected."
        },
        "13": {
          "caption": "Uncorrected",
          "description": "A corrupt file or configuration was not corrected."
        },
        "14": {
          "caption": "Delayed",
          "description": "An operation was delayed, for example if a restart was required to finish the operation."
        },
        "15": {
          "caption": "Detected",
          "description": "Suspicious activity or a policy violation was detected without further action."
        },
        "16": {
          "caption": "No Action",
          "description": "The outcome of an operation had no action taken."
        },
        "17": {
          "caption": "Logged",
          "description": "The operation or action was logged without further action."
        },
        "18": {
          "caption": "Tagged",
          "description": "A file or other entity was marked with extended attributes."
        },
        "19": {
          "caption": "Alert",
          "description": "Threat or URL detected but not blocked. This is a non-terminating action."
        },
        "20": {
          "caption": "Count",
          "description": "For firewalls, counted the request but did not determine whether to allow it or block it. This is a network non-terminating action. May insert custom headers into the request and add labels that other rules can match against."
        },
        "21": {
          "caption": "Reset",
          "description": "For firewalls, a threat or URL was detected. This is a network non-terminating action."
        },
        "22": {
          "caption": "Captcha",
          "description": "Required the end user to solve a CAPTCHA puzzle to prove that a human being is sending the request. This is a network non-terminating action."
        },
        "23": {
          "caption": "Challenge",
          "description": "Ran a silent challenge that required the client session to verify that it's a browser, and not a bot. This is a network non-terminating action."
        },
        "24": {
          "caption": "Access Revoked",
          "description": "The requestor's access has been revoked due to security policy enforcements.  Note: use the <code>Host</code> profile if the <code>User</code> or <code>Actor</code> requestor is not present in the event class."
        },
        "25": {
          "caption": "Rejected",
          "description": "A request or submission was rejected.  For example, when a form was improperly filled out and submitted.  This is distinct from '<code>Blocked</code>'."
        }
      }
    },
    "firewall_rule": {
      "requirement": "optional"
    },
    "malware": {
      "requirement": "optional"
    }
  }
}

=== 02manoj92/ocsf-schema/profiles/person.json
{
  "description": "The additonal attributes that describe a person or user beyond those required for a user. These are expected to be used primarily to add additional context for the <code>user_inventory</code> event class.",
  "meta": "profile",
  "caption": "Person",
  "name": "person",
  "annotations": {
    "group": "primary"
  },
  "attributes": {
    "cost_center": {
      "requirement": "optional"
    },
    "created_time": {
      "description": "The timestamp when the user was created.",
      "requirement": "optional"
    },
    "deleted_time": {
      "requirement": "optional"
    },
    "employee_uid": {
      "requirement": "optional"
    },
    "given_name": {
      "requirement": "optional"
    },
    "hire_datetime": {
      "requirement": "optional"
    },
    "job_title": {
      "requirement": "optional"
    },
    "labels": {
      "description": "The labels associated with the user. For example in AD this could be the <code>userType</code>, <code>employeeType</code>. For example: <code>Member, Employee</code>",  
      "requirement": "optional"
    },
    "last_login_time": {
      "requirement": "optional"
    },
    "leave_datetime": {
      "requirement": "optional"
    },
    "location": {
      "description": "The detailed geographical location associated with a user. When used with the <code>user_inventory</code> event class, this typically documents the users usual work location.",
      "requirement": "optional"
    },
    "manager": {
      "requirement": "optional"
    },
    "modified_time": {
      "description":"The timestamp when the user entry was last modified",
      "requirement": "optional"
    },
    "office_location": {
      "requirement": "optional"
    },
    "email_addresses": {
      "caption": "Email Addresses",
      "group": "context",
      "requirement": "optional"
    },
    "surname": {
      "requirement": "optional"
    }
  }
}

=== 02manoj92/ocsf-schema/profiles/file_security.json
{
  "description": "The file attributes that are associated with security software.",
  "meta": "profile",
  "caption": "File Security",
  "name": "file_security",
  "attributes": {
    "confidentiality": {
      "requirement": "optional"
    },
    "confidentiality_id": {
      "requirement": "optional"
    },
    "fingerprints": {
      "requirement": "recommended"
    },
    "signature": {
      "requirement": "optional"
    }
  }
}

=== 02manoj92/ocsf-schema/profiles/domain_info.json
{
  "description": "The domain registrar information.",
  "meta": "profile",
  "caption": "Domain",
  "name": "domain_info",
  "attributes": {
    "confidentiality": {
      "requirement": "optional"
    },
    "confidentiality_id": {
      "requirement": "optional"
    },
    "fingerprints": {
      "requirement": "recommended"
    },
    "signature": {
      "requirement": "optional"
    },
    "md5": {
      "requirement": "recommended"
    },
    "sha1": {
      "requirement": "recommended"
    },
    "sha2": {
      "requirement": "recommended"
    }
  }
}
